version: "3.9"
services:
  db:
    image: postgres:16-alpine
    container_name: maga_test_db
    environment:
      POSTGRES_DB: maga_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "admin"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  pgdata:
